# Import Numpy

In [1]:
import numpy as np

# The Basics

In [17]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[5.0,6.0,4.0]])
print(b)

[[9. 8. 7.]
 [5. 6. 4.]]


In [12]:
#Get Dimentions
A = a.ndim
B = b.ndim
print(A,B)

1 2


In [13]:
# Get Shape
b.shape

(2, 3)

In [18]:
# Get Data Type
a.dtype

dtype('int32')

In [20]:
# If you wants to change the data type
a = np.array([1,2,3], dtype = 'int16')
print(a)

[1 2 3]


In [21]:
a.dtype

dtype('int16')

In [22]:
# Get Size (Number of bytes)
a.itemsize

2

In [25]:
# Get total size
a.size * a.itemsize
# or

a.nbytes

6

In [30]:
# For B

print(b.dtype)
print(b.size)
print(b.itemsize)
print(b.nbytes)

float64
6
8
48


# Accessing/Changing specific elements, rows, columns, ect.

In [82]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [34]:
# Get specific element (row,column)
a[1,5]

13

In [35]:
# Get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [36]:
# Get specific column
a[:,2]

array([ 3, 10])

In [45]:
# Getting a little more fancy [ startingindex:endingindex:stepindex]
#Get the values between 1st row 2col to 6 col step by 2
print(a[0,1:6:2])
print(a[0,1:-1:2])

# same to 2nd row
print(a[1,1:6:2])
print(a[1,1:-1:2])


[2 4 6]
[2 4 6]
[ 9 11 13]
[ 9 11 13]


In [54]:
# Change the element value
q = a[1,5] = 20
print(q)

p = a[:,3] = 5
print(p)

a

20
5


array([[ 1,  2,  3,  5,  5,  6,  7],
       [ 8,  9, 10,  5, 12, 20, 14]])

In [55]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  5  5  6  7]
 [ 8  9  2  5 12 20 14]]


3D Example

In [57]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [60]:
# Get specific element (work from outside)
print(b[0,1,:])
print(b[1,0,:])
print(b[:,1,1])

[3 4]
[5 6]
[4 8]


In [63]:
#replace
b[:,1,:] = [[9,9],[8,8]]
print(b)
b[:,0,1] = 9
print(b)

[[[1 9]
  [9 9]]

 [[5 9]
  [8 8]]]
[[[1 9]
  [9 9]]

 [[5 9]
  [8 8]]]


# Initializing Different type of Arrays

In [72]:
#All 0s matrix
np.zeros((2,5,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [79]:
#All ones
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [81]:
#Any other number
np.full((3,3), 23, dtype = 'float32')

array([[23., 23., 23.],
       [23., 23., 23.],
       [23., 23., 23.]], dtype=float32)

In [85]:
#Any other full_like
print(np.full_like(a,4))
#or
print(np.full(a.shape,4))

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [89]:
# Random decimal numbers
print(np.random.rand(4,2))
print(np.random.random_sample(a.shape))


[[0.89758963 0.81010285]
 [0.0941076  0.00833869]
 [0.0467327  0.89086987]
 [0.61031946 0.17593491]]
[[0.09407294 0.04947641 0.80873275 0.15106181 0.38021903 0.37424195
  0.44819719]
 [0.90250416 0.70738299 0.900089   0.36077598 0.11316339 0.72246031
  0.59007766]]


In [96]:
# Random integer values
np.random.randint(2,10,size= (3,3))

array([[2, 3, 7],
       [3, 8, 7],
       [7, 8, 8]])

In [97]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [106]:
array = np.array([[1,2,3]])
r1 = np.repeat(array,3, axis =0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

Ex

In [119]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)

z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [123]:
# Copy
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


# Mathematics

In [144]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [129]:
a+2
#or
a +=2
a

array([3, 4, 5, 6])

In [132]:
a- 2

array([-1,  0,  1,  2])

In [134]:
a * 3

array([ 3,  6,  9, 12])

In [136]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [143]:
b = np.array([1,0,1,0])
a + B

array([3, 4, 5, 6])

In [140]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [148]:
#Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

https://numpy.org/doc/stable/reference/routines.math.html

#### Linear Algebra

In [153]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [155]:
#Matrix Multipication

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [156]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

https://numpy.org/doc/stable/reference/routines.linalg.html

### Reorganizing Array

In [159]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)
print(before)

after = before.reshape((8,1))
print(after)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [162]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [164]:
# Horizontal stacking vactors

h1 =np.ones((2,4))
h2 =np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

##Load Data from Taxt file

In [173]:
filedata = np.genfromtxt('filedata.txt' , delimiter = ',')
filedata = filedata.astype('float32')
filedata

array([[13.  ,  2.  ,  4.  ,  5.  ,  6.  ],
       [39.4 , 46.  , 38.  ,  3.  , 23.  ],
       [12.  , 32.  , 45.  , 56.  ,  4.56]], dtype=float32)

### Boolean Masking and Advanced Indexing

In [174]:
filedata>30

array([[False, False, False, False, False],
       [ True,  True,  True, False, False],
       [False,  True,  True,  True, False]])

In [175]:
# Index elements
filedata[filedata > 30]

array([39.4, 46. , 38. , 32. , 45. , 56. ], dtype=float32)

In [178]:
np.any(filedata > 30 , axis = 0) #axis = 0 means Columns and 1 means rows

array([ True,  True,  True,  True, False])

In [181]:
print(((filedata >30 ) & (filedata <40)))
print((~((filedata >30 ) & (filedata <40)))) # not greter than 30 and less than 40

[[False False False False False]
 [ True False  True False False]
 [False  True False False False]]
[[ True  True  True  True  True]
 [False  True False  True  True]
 [ True False  True  True  True]]


In [190]:
Q1 = np.ones([6,5])
Q1
# index 3rd and 4th rows 1st two columns elements
Q1[2:4,0:2]


array([[1., 1.],
       [1., 1.]])